export const SET_INCLUDE_COMPS = 'SET_INCLUDE_COMPS'
export const SET_LOADING = 'SET_LOADING'
export const SET_TAB_ACTIVE = 'SET_TAB_ACTIVE'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_ID = 'SET_ID'
export const SET_USERINFO = 'SET_USERINFO'
export const SET_PATH = 'SET_PATH'
